name: Build and Validate Python Package

on:
  push:

jobs:
  validate-distribution:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        run: python -m build

      - name: Check distribution packages with twine
        run: twine check dist/*

      - name: Inspect wheel package contents
        run: unzip -l dist/alertalot-*.whl

      - name: Create test virtual environment
        run: python -m venv venv_test

      - name: Install package in test environment
        run: |
          source venv_test/bin/activate
          pip install dist/alertalot-*-none-any.whl
          alertalot --help
