name: Run Tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python3.10 -m venv venv
          pip install -e .[dev]
          source venv/bin/activate

      - name: Run tests
        run: |
          pytest --cov=alertalot --cov-report=xml --cov-branch --cov-fail-under=25

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Run pylint on alertalot
        run: |
          pylint alertalot --rcfile=.pylintrc --fail-under 10

      - name: Run pylint on tests
        run: |
          pylint tests --rcfile=tests/.pylintrc --fail-under 10