name: Publish New Version


on:
  push:
    tags:
      - 'v*'

jobs:
  unittests:
    uses: ./.github/workflows/_tests.yaml

  publish-local-test:
    uses: ./.github/workflows/_publish_local.yaml

  publish-pypi:
    needs:
      - unittests
      - publish-local-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # Make sure the version defined in the library,
      # matches the version in pyproject.toml
      - name: Validate Versions Match
        run: |
          ./bin/validate_version.sh

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        run: python -m build

      - name: Check distribution packages with twine
        run: twine check dist/*

      - name: Upload to PyPi
        run: twine upload dist/alertalot-* -u __token__ -p ${{ secrets.PYPI_TOKEN }}
